server:
  port: 80

spring:
  application:
    name: cloud-order-server
  #链路追踪
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率，0-1直接，1表示全部采集
        probability: 1